export const AUTH_TOKEN_SECRET = 'AUTH_TOKEN_SECRET';

export const AUTH_EMAIL_USER = 'AUTH_EMAIL_USER';
export const AUTH_EMAIL_HOST = 'AUTH_EMAIL_HOST';
export const AUTH_EMAIL_PORT = 'AUTH_EMAIL_PORT';
export const AUTH_EMAIL_PASSWORD = 'AUTH_EMAIL_PASSWORD';

export const FULL_HOST_URLS = 'FULL_HOST_URLS';

export const BACKEND_URL = 'BACKEND_URL';
export const VERSION = 'VERSION';
export const DEPLOY_DATE = 'DEPLOY_DATE';

export const SESSION_SECRET1 = 'SESSION_SECRET1';
export const SESSION_SECRET2 = 'SESSION_SECRET2';

export const ALLOW_CORS = 'ALLOW_CORS';

export const USER_ENCRYPT_KEY = 'USER_ENCRYPT_KEY';
export const USER_ENCRYPT_IV = 'USER_ENCRYPT_IV';

export const MAGIC_LINK_ENCRYPT_KEY = 'MAGIC_LINK_ENCRYPT_KEY';
export const MAGIC_LINK_ENCRYPT_IV = 'MAGIC_LINK_ENCRYPT_IV';

export const COOKIE_SECRET = 'COOKIE_SECRET';

export const CSRF_SECRET = 'CSRF_SECRET';